version: "3"
services:
  backend:
    build: 
      context: ./mercado_api
      dockerfile: Dockerfile
    ports:
      - "1027:10369"
  
  frontend:
    build: 
      context: ./mercado_web
      dockerfile: Dockerfile
    env_file:
      - ./mercado_web/.env
    ports:
      - "1028:3000"      
    depends_on:
      - backend