version: "3"
services:
  api:
    build: .
    ports:
      - "1027:10369"
  
  web_client:
    build: 
      context: ../mercado_
      dockerfile: Dockerfile
    ports:
      - "1028:3000"      
    depends_on:
      - api 
    links:
      - api
